language: php
php:
- 7.0
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_install:
- openssl aes-256-cbc -K $encrypted_e8fb50739bd8_key -iv $encrypted_e8fb50739bd8_iv
  -in travis-secrets.tar.enc -out travis-secrets.tar -d
- tar xvf travis-secrets.tar
install:
- composer install
script: vendor/bin/phpunit  --coverage-clover build/logs/clover.xml
after_success:
- if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then travis_retry php vendor/bin/coveralls
  -v; fi
